### PR TITLE
RemovingTitleTag

### PR DESCRIPTION
**Pull request by rakesh-santra9**
Need to remove Title Tag as its showing inappropriate Tooltip

wrongtooltip

### CODE REVIEW

**Comment by monoguerin** [comment]
seems fine to me, but maybe will be helpful for others thinking about accessibility, I will like to handle this with a config param, something that you can add in the loader config so there you can delete this titles

**Comment by rakesh-santra9** [comment]
@monoguerin , make sense to me. It will be better if we add config param to toggle Title Tag.
Also is there a way  to pass title while registering SVG Icon as a component inside VueJS file?

**Comment by monoguerin** [comment]
@rakesh-santra9 yeah I will work on a fix that allow us to pass if we rather want or not the title tag, currently I haven't plan anything related to passing the title to the component, the only thing that this loader creates is the render function, if we find out a good way on passing the title maybe with any special character after the id name of the icon that will be possible, It should be in the import statement as each icon may have a different title

**Comment by rakesh-santra9** [comment]
Thanks @monoguerin, please take you time to work on passing Title argument. Till that time shall we remove title tag?

**Comment by monoguerin** [comment]
@rakesh-santra9 done please check PR #7

**Comment by monoguerin** [comment]
@rakesh-santra9 This was handled by PR #7 and was published under version **1.2.0**, Thanks

**Pull request closed without merging**
